

--DROP PROCEDURE INSERT_PROP_REGRESS_AVM_0
CREATE PROCEDURE [dbo].[INSERT_PROP_REGRESS_AVM_0] 
@DEPVAR NVARCHAR(100), @MDRA NVARCHAR(255),@SUBTYPE NVARCHAR(25),@STATEMENTYEAR2 INT, 
@MIN_NUMPROPS_FOR_US_MEAN_CALC INT,@MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL INT,
@UWDATE_START DATE,@UWDATE_END DATE   
AS

BEGIN

BEGIN TRY

--DECLARE @DEPVAR NVARCHAR(100), @MDRA NVARCHAR(255),@SUBTYPE NVARCHAR(25),@STATEMENTYEAR2 INT, @MIN_NUMPROPS_FOR_US_MEAN_CALC INT,@MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL INT,@UWDATE_START DATE,@UWDATE_END DATE      
--select @DEPVAR='uw_caprate', @MDRA='southeast',@SUBTYPE='garden',@STATEMENTYEAR2=2020, @MIN_NUMPROPS_FOR_US_MEAN_CALC=100,@MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL=20,@UWDATE_START=DATEFROMPARTS(2020,6,1),@UWDATE_END=DATEFROMPARTS(2021,6,1)     


DECLARE @MODELNUM INT,@NUMVAR INT
SELECT @MODELNUM=0,@NUMVAR=2

DECLARE @MDRA_SUBTYPE_YR1_YR2_VAR_NUM NVARCHAR(255),@MDRA_SUBTYPE_YR1_YR2 NVARCHAR(255),@MDRA_SUBTYPE_VAR NVARCHAR(255),@MDRA_SUBTYPE_YR2_VAR NVARCHAR(255),@MDRA_SUBTYPE_YR2 NVARCHAR(255),
@I1 INT,@I2 INT,@I3 INT,@I4 INT,@I5 INT,
@MEAN1 FLOAT,@MEAN2 FLOAT,@MEAN3 FLOAT,@MEAN4 FLOAT,@MEAN5 FLOAT,
@SDV1 FLOAT,@SDV2 FLOAT,@SDV3 FLOAT,@SDV4 FLOAT,@SDV5 FLOAT,
@COEFF1 FLOAT,@COEFF2 FLOAT,@COEFF3 FLOAT,@COEFF4 FLOAT,@COEFF5 FLOAT,
@VAR1 AS NVARCHAR(255),@VAR2 AS NVARCHAR(255),@VAR3 AS NVARCHAR(255),@VAR4 AS NVARCHAR(255),@VAR5 AS NVARCHAR(255),
@C1 FLOAT,@C2 FLOAT,@C3 FLOAT,@C4 FLOAT,@C5 FLOAT,@C6 FLOAT,@C7 FLOAT,@C8 FLOAT,@C9 FLOAT,@C10 FLOAT,@C11 FLOAT,@C12 FLOAT,@C13 FLOAT,@C14 FLOAT,@C15 FLOAT,@C16 FLOAT,@C17 FLOAT,@C18 FLOAT,@C19 FLOAT,@C20 FLOAT,@C21 FLOAT,@C22 FLOAT,@C23 FLOAT,@C24 FLOAT,@C25 FLOAT,@C26 FLOAT,@C27 FLOAT,@C28 FLOAT,@C29 FLOAT,@C30 FLOAT,@C31 FLOAT,@C32 FLOAT,@C33 FLOAT,@C34 FLOAT,@C35 FLOAT,@C36 FLOAT,@C37 FLOAT,@C38 FLOAT,@C39 FLOAT,@C40 FLOAT,@C41 FLOAT,@C42 FLOAT,@C43 FLOAT,
@CORREL1 FLOAT,@CORREL2 FLOAT,@CORREL3 FLOAT,@CORREL4 FLOAT,@CORREL5 FLOAT,@CORREL6 FLOAT,@CORREL7 FLOAT,@CORREL8 FLOAT,@CORREL9 FLOAT,@CORREL10 FLOAT,@CORREL11 FLOAT,@CORREL12 FLOAT,@CORREL13 FLOAT,@CORREL14 FLOAT,@CORREL15 FLOAT,@CORREL16 FLOAT,@CORREL17 FLOAT,@CORREL18 FLOAT,@CORREL19 FLOAT,@CORREL20 FLOAT,@CORREL21 FLOAT,@CORREL22 FLOAT,@CORREL23 FLOAT,@CORREL24 FLOAT,@CORREL25 FLOAT,@CORREL26 FLOAT,@CORREL27 FLOAT,@CORREL28 FLOAT,@CORREL29 FLOAT,@CORREL30 FLOAT,@CORREL31 FLOAT,@CORREL32 FLOAT,@CORREL33 FLOAT,@CORREL34 FLOAT,@CORREL35 FLOAT,@CORREL36 FLOAT,@CORREL37 FLOAT,@CORREL38 FLOAT,@CORREL39 FLOAT,@CORREL40 FLOAT,@CORREL41 FLOAT,@CORREL42 FLOAT,@CORREL43 FLOAT,

@X1 FLOAT,@X2 FLOAT,@X3 FLOAT,@X4 FLOAT,@X5 FLOAT,@X6 FLOAT,@X7 FLOAT,@X8 FLOAT,@X9 FLOAT,@X10 FLOAT,@X11 FLOAT,@X12 FLOAT,@X13 FLOAT,@X14 FLOAT,@X15 FLOAT,@X16 FLOAT,@X17 FLOAT,@X18 FLOAT,@X19 FLOAT,@X20 FLOAT,@X21 FLOAT,@X22 FLOAT,@X23 FLOAT,@X24 FLOAT,@X25 FLOAT,@X26 FLOAT,@X27 FLOAT,@X28 FLOAT,@X29 FLOAT,@X30 FLOAT,@X31 FLOAT,@X32 FLOAT,@X33 FLOAT,@X34 FLOAT,@X35 FLOAT,@X36 FLOAT,@X37 FLOAT,@X38 FLOAT,@X39 FLOAT,@X40 FLOAT,@X41 FLOAT,@X42 FLOAT,@X43 FLOAT,
@MEAN0 FLOAT,@SDV0 FLOAT,
@RSQUARE1 FLOAT,@RSQUARE2 FLOAT,@RSQUARE3 FLOAT,@RSQUARE4 FLOAT,@RSQUARE5 FLOAT,
@STDERROR1 FLOAT,@STDERROR2 FLOAT,@STDERROR3 FLOAT,@STDERROR4 FLOAT,@STDERROR5 FLOAT,
@RSQUARE FLOAT,@STDERROR FLOAT,
@MEAN FLOAT,@SDV FLOAT, @MAXCORREL FLOAT,@NUM INT,@I INT, 
@BIG FLOAT,@SMALL FLOAT,@NUMOBSERVATIONS INT,@STATEMENTYEAR1 INT,@NUMPROPERTIES BIGINT,@NUMPROPYEAR BIGINT
SELECT @BIG=10000000000,@SMALL=0

DECLARE @NumProperties_UW FLOAT,@NumProperties_NOI_3YR_CH_FWD FLOAT,@NumProperties_NOI_1YR_CH_FWD FLOAT,@NumProperties_REV_1YRCH FLOAT,@NumProperties_FF FLOAT

--CHECK IF THERE ARE 1) ENOUGH OBSERVATIONS AND 2) US MEAN IS CALCULATED

--ALL US NUMBERS
SELECT @NumProperties_UW=(SELECT MAX(NumProperties_UW) FROM MACRO_MEAN_SDV M WHERE M.SUBTYPE='ALL' AND M.MDRA='ALLUS' AND M.STATEMENTYEAR=@STATEMENTYEAR2)
--SUBTYPE_MDRA SDV

IF @NumProperties_UW>@MIN_NUMPROPS_FOR_US_MEAN_CALC
AND
(SELECT COUNT(*) FROM LPLIST_AVM WHERE UWDATE>=@UWDATE_START AND UWDATE<=@UWDATE_END   
AND (NCREIFMETRO=@MDRA OR NCREIFDIVISION=@MDRA OR NCREIFREGION=@MDRA OR @MDRA='ALLUS') AND (PropertySubType_ASSIGNED=@SUBTYPE OR @SUBTYPE='ALL' OR ((PropertySubType_ASSIGNED='GARDEN' OR PropertySubType_ASSIGNED='MIDRISE') AND @SUBTYPE='GARDEN_MIDRISE') OR ((PropertySubType_ASSIGNED='MIDRISE' OR PropertySubType_ASSIGNED='HIRISE') AND @SUBTYPE='MIDRISE_HIRISE') OR ((PropertySubType_ASSIGNED='GARDEN' OR PropertySubType_ASSIGNED='MIDRISE' OR PropertySubType_ASSIGNED='HIRISE') AND @SUBTYPE='GARDEN_MIDRISE_HIRISE') OR ((PropertySubType_ASSIGNED='GARDEN(SB)' OR PropertySubType_ASSIGNED='GARDEN') AND @SUBTYPE='GARDEN(ALL)') OR ((PropertySubType_ASSIGNED='MIDRISE(SB)' OR PropertySubType_ASSIGNED='MIDRISE') AND @SUBTYPE='MIDRISE(ALL)') OR ((PropertySubType_ASSIGNED='GARDEN(SB)' OR PropertySubType_ASSIGNED='MIDRISE(SB)') AND @SUBTYPE='GARDEN_MIDRISE(SB)'))
AND (DATANUM=0 OR DATANUM=1 OR DATANUM=2 OR DATANUM=3)
AND
CASE WHEN @DEPVAR='UW_CAPRATE' THEN UW_CAPRATE 
ELSE CASE WHEN @DEPVAR='UW_REV_ACTUAL_RATIO' THEN UW_REV_ACTUAL_RATIO
ELSE CASE WHEN @DEPVAR='UW_EXP_ACTUAL_RATIO' THEN UW_EXP_ACTUAL_RATIO
END END END IS NOT NULL)
>=@MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL

BEGIN---PERFORM THE CALC

SELECT @STATEMENTYEAR1=@STATEMENTYEAR2

--PERFORM THE CALC
SELECT 
@MDRA_SUBTYPE_YR1_YR2_VAR_NUM=CONCAT(@MDRA,'_',@SUBTYPE,'_',@STATEMENTYEAR1,'_',@STATEMENTYEAR2,'_',@DEPVAR,'_',@MODELNUM),
@MDRA_SUBTYPE_YR1_YR2=CONCAT(@MDRA,'_',@SUBTYPE,'_',@STATEMENTYEAR1,'_',@STATEMENTYEAR2),
@MDRA_SUBTYPE_YR2_VAR=CONCAT(@MDRA,'_',@SUBTYPE,'_',@STATEMENTYEAR2,'_',@DEPVAR),
@MDRA_SUBTYPE_VAR=CONCAT(@MDRA,'_',@SUBTYPE,'_',@DEPVAR),
@MDRA_SUBTYPE_YR2=CONCAT(@MDRA,'_',@SUBTYPE,'_',@STATEMENTYEAR2)

--SUBTYPE_MDRA SDV

SELECT DISTINCT
STATEMENTYEAR=M.STATEMENTYEAR,
NUMPROPYEAR=(SELECT COUNT(*) FROM LPLIST_AVM WHERE UWDATE>=@UWDATE_START  AND UWDATE<=@UWDATE_END   
AND (NCREIFMETRO=@MDRA OR NCREIFDIVISION=@MDRA OR NCREIFREGION=@MDRA OR @MDRA='ALLUS') AND (PropertySubType_ASSIGNED=@SUBTYPE OR @SUBTYPE='ALL' OR ((PropertySubType_ASSIGNED='GARDEN' OR PropertySubType_ASSIGNED='MIDRISE') AND @SUBTYPE='GARDEN_MIDRISE') OR ((PropertySubType_ASSIGNED='MIDRISE' OR PropertySubType_ASSIGNED='HIRISE') AND @SUBTYPE='MIDRISE_HIRISE') OR ((PropertySubType_ASSIGNED='GARDEN' OR PropertySubType_ASSIGNED='MIDRISE' OR PropertySubType_ASSIGNED='HIRISE') AND @SUBTYPE='GARDEN_MIDRISE_HIRISE') OR ((PropertySubType_ASSIGNED='GARDEN(SB)' OR PropertySubType_ASSIGNED='GARDEN') AND @SUBTYPE='GARDEN(ALL)') OR ((PropertySubType_ASSIGNED='MIDRISE(SB)' OR PropertySubType_ASSIGNED='MIDRISE') AND @SUBTYPE='MIDRISE(ALL)') OR ((PropertySubType_ASSIGNED='GARDEN(SB)' OR PropertySubType_ASSIGNED='MIDRISE(SB)') AND @SUBTYPE='GARDEN_MIDRISE(SB)'))
AND (DATANUM=0 OR DATANUM=1 OR DATANUM=2 OR DATANUM=3)
AND
CASE WHEN @DEPVAR='UW_CAPRATE' THEN UW_CAPRATE 
ELSE CASE WHEN @DEPVAR='UW_REV_ACTUAL_RATIO' THEN UW_REV_ACTUAL_RATIO
ELSE CASE WHEN @DEPVAR='UW_EXP_ACTUAL_RATIO' THEN UW_EXP_ACTUAL_RATIO
END END END IS NOT NULL),

V=CASE WHEN @DEPVAR='UW_CAPRATE' THEN M.UW_CAPRATE
ELSE CASE WHEN @DEPVAR='UW_REV_ACTUAL_RATIO' THEN M.UW_REV_ACTUAL_RATIO 
ELSE CASE WHEN @DEPVAR='UW_EXP_ACTUAL_RATIO' THEN M.UW_EXP_ACTUAL_RATIO 
END END END, 

YearBuiltRenov=M.YearBuiltRenov,
PopulationPerSqMile=M.PopulationPerSqMile,
MedianHHInc=M.MedianHHInc,
MedianHomeVal=M.MedianHomeVal,
Median_Rent=M.Median_Rent,
MedianAge=M.MedianAge,
Median_Owner_Costs=M.Median_Owner_Costs,
RenterPCT=M.RenterPCT,
CashRentOver30PCT=M.CashRentOver30PCT,
BachelorsOrMorePCT=M.BachelorsOrMorePCT,
UnemploymentPCT=M.UnemploymentPCT,
MngtFinancePCT=M.MngtFinancePCT,
MovedIn2010orLaterPCT=M.MovedIn2010orLaterPCT,
HPI_1YRCH=M.HPI_1YRCH,
--OCCUP=M.OCCUP,
--REV_PERUNIT=M.REV_PERUNIT,
--EXP_PCTREV=M.EXP_PCTREV,
--CAPEX_PCTREV=M.CAPEX_PCTREV,
--OCCUP_1YRCH=M.OCCUP_1YRCH,
--REV_1YR_PCT_CH=M.REV_1YR_PCT_CH,
--EXP_1YR_PCT_CH=M.EXP_1YR_PCT_CH,
--YearBuilt=M.YearBuilt,
NumUnits=M.NumUnits,
--RevenuePctMedianIncome=M.RevenuePctMedianIncome,
--NOI_1YR_PCT_CH=M.NOI_1YR_PCT_CH,
HPI_METRO_1YRCH=M.HPI_METRO_1YRCH
--RETAXES_PCTREV=M.RETAXES_PCTREV,
--PROPINS_PCTREV=M.PROPINS_PCTREV,
--UTILITI_PCTREV=M.UTILITI_PCTREV,
--REPAIRS_PCTREV=M.REPAIRS_PCTREV,
--MANAGEM_PCTREV=M.MANAGEM_PCTREV,
--PAYROLL_PCTREV=M.PAYROLL_PCTREV

INTO #TUS
FROM MACRO_MEAN_SDV M WHERE M.SUBTYPE='ALL' AND M.MDRA='ALLUS' AND M.STATEMENTYEAR>=@STATEMENTYEAR1 AND M.STATEMENTYEAR<=@STATEMENTYEAR2 
AND M.NumProperties_UW>@MIN_NUMPROPS_FOR_US_MEAN_CALC

SELECT DISTINCT
STATEMENTYEAR=M.STATEMENTYEAR,
V=
CASE WHEN @DEPVAR='UW_CAPRATE' THEN P.UW_CAPRATE
ELSE CASE WHEN @DEPVAR='UW_REV_ACTUAL_RATIO' THEN P.UW_REV_ACTUAL_RATIO
ELSE CASE WHEN @DEPVAR='UW_EXP_ACTUAL_RATIO' THEN P.UW_EXP_ACTUAL_RATIO
END END END
-M.V, 

V1=P.YearBuiltRenov-M.YearBuiltRenov,
V2=P.PopulationPerSqMile-M.PopulationPerSqMile,
V3=P.MedianHHInc-M.MedianHHInc,
V4=P.MedianHomeVal-M.MedianHomeVal,
V5=P.Median_Rent-M.Median_Rent,
V6=P.MedianAge-M.MedianAge,
V7=P.Median_Owner_Costs-M.Median_Owner_Costs,
V8=P.RenterPCT-M.RenterPCT,
V9=P.CashRentOver30PCT-M.CashRentOver30PCT,
V10=P.BachelorsOrMorePCT-M.BachelorsOrMorePCT,
V11=P.UnemploymentPCT-M.UnemploymentPCT,
V13=P.MngtFinancePCT-M.MngtFinancePCT,
V15=P.MovedIn2010orLaterPCT-M.MovedIn2010orLaterPCT,
V16=P.HPI_1YRCH-M.HPI_1YRCH,
--V17=P.OCCUP-M.OCCUP,
--V18=P.REV_PERUNIT-M.REV_PERUNIT,
--V19=P.EXP_PCTREV-M.EXP_PCTREV,
--V27=P.CAPEX0_PCTREV-M.CAPEX_PCTREV,
--V29=P.OCCUP_1YRCH-M.OCCUP_1YRCH,
--V30=P.REV_1YR_PCT_CH-M.REV_1YR_PCT_CH,
--V31=P.EXP_1YR_PCT_CH-M.EXP_1YR_PCT_CH,
--V34=P.YearBuilt-M.YearBuilt,
V35=P.NumUnits-M.NumUnits,
--V36=P.RevenuePctMedianIncome-M.RevenuePctMedianIncome,
--V38=P.NOI_1YR_PCT_CH-M.NOI_1YR_PCT_CH,
V39=P.HPI_METRO_1YRCH-M.HPI_METRO_1YRCH

--V20=P.RETAXES_PCTREV-M.RETAXES_PCTREV,
--V21=P.PROPINS_PCTREV-M.PROPINS_PCTREV,
--V40=P.UTILITI_PCTREV-M.UTILITI_PCTREV,
--V41=P.REPAIRS_PCTREV-M.REPAIRS_PCTREV,
--V42=P.MANAGEM_PCTREV-M.MANAGEM_PCTREV,
--V43=P.PAYROLL_PCTREV-M.PAYROLL_PCTREV

INTO #T0
FROM #TUS M,LPLIST_AVM P WHERE UWDATE>=@UWDATE_START  AND UWDATE<=@UWDATE_END 
AND M.STATEMENTYEAR=@STATEMENTYEAR2 
AND (P.NCREIFMETRO=@MDRA OR P.NCREIFDIVISION=@MDRA OR P.NCREIFREGION=@MDRA OR @MDRA='ALLUS') 
AND (P.PropertySubType_ASSIGNED=@SUBTYPE OR @SUBTYPE='ALL' OR ((P.PropertySubType_ASSIGNED='GARDEN' OR P.PropertySubType_ASSIGNED='MIDRISE') AND @SUBTYPE='GARDEN_MIDRISE') OR ((P.PropertySubType_ASSIGNED='MIDRISE' OR P.PropertySubType_ASSIGNED='HIRISE') AND @SUBTYPE='MIDRISE_HIRISE') OR ((P.PropertySubType_ASSIGNED='GARDEN' OR P.PropertySubType_ASSIGNED='MIDRISE' OR P.PropertySubType_ASSIGNED='HIRISE') AND @SUBTYPE='GARDEN_MIDRISE_HIRISE') OR ((P.PropertySubType_ASSIGNED='GARDEN(SB)' OR P.PropertySubType_ASSIGNED='GARDEN') AND @SUBTYPE='GARDEN(ALL)') OR ((P.PropertySubType_ASSIGNED='MIDRISE(SB)' OR P.PropertySubType_ASSIGNED='MIDRISE') AND @SUBTYPE='MIDRISE(ALL)') OR ((P.PropertySubType_ASSIGNED='GARDEN(SB)' OR P.PropertySubType_ASSIGNED='MIDRISE(SB)') AND @SUBTYPE='GARDEN_MIDRISE(SB)'))

AND P.YearBuiltRenov IS NOT NULL
AND P.PopulationPerSqMile IS NOT NULL
AND P.MedianHHInc IS NOT NULL
AND P.MedianHomeVal IS NOT NULL
AND P.Median_Rent IS NOT NULL
AND P.MedianAge IS NOT NULL
AND P.Median_Owner_Costs IS NOT NULL
AND P.RenterPCT IS NOT NULL
AND P.CashRentOver30PCT IS NOT NULL
AND P.BachelorsOrMorePCT IS NOT NULL
AND P.UnemploymentPCT IS NOT NULL
AND P.MngtFinancePCT IS NOT NULL
AND P.MovedIn2010orLaterPCT IS NOT NULL
AND P.HPI_1YRCH IS NOT NULL
--AND P.OCCUP IS NOT NULL
--AND P.REV_PERUNIT IS NOT NULL
--AND P.EXP_PCTREV IS NOT NULL
--AND P.CAPEX_PCTREV IS NOT NULL
--AND P.OCCUP_1YRCH IS NOT NULL
--AND P.REV_1YR_PCT_CH IS NOT NULL
--AND P.EXP_1YR_PCT_CH IS NOT NULL
--AND P.YearBuilt IS NOT NULL
AND P.NumUnits IS NOT NULL
--AND P.RevenuePctMedianIncome IS NOT NULL
--AND P.NOI_1YR_PCT_CH IS NOT NULL
--AND P.HPI_METRO_1YRCH IS NOT NULL
--AND P.RETAXES_PCTREV IS NOT NULL
--AND P.PROPINS_PCTREV IS NOT NULL
--AND P.UTILITI_PCTREV IS NOT NULL
--AND P.REPAIRS_PCTREV IS NOT NULL
--AND P.MANAGEM_PCTREV IS NOT NULL
--AND P.PAYROLL_PCTREV IS NOT NULL
AND
CASE WHEN @DEPVAR='UW_CAPRATE' THEN P.UW_CAPRATE
ELSE CASE WHEN @DEPVAR='UW_REV_ACTUAL_RATIO' THEN P.UW_REV_ACTUAL_RATIO
ELSE CASE WHEN @DEPVAR='UW_EXP_ACTUAL_RATIO' THEN P.UW_EXP_ACTUAL_RATIO
END END END IS NOT NULL

DROP TABLE #TUS

SELECT @NUMPROPYEAR=10000
DECLARE @STATEMENTYEAR INT
SELECT @STATEMENTYEAR=@STATEMENTYEAR2
WHILE @STATEMENTYEAR>=@STATEMENTYEAR1
BEGIN
	IF (SELECT COUNT(*) FROM #T0 WHERE STATEMENTYEAR=@STATEMENTYEAR)<@NUMPROPYEAR SELECT @NUMPROPYEAR=(SELECT COUNT(*) FROM #T0 WHERE STATEMENTYEAR=@STATEMENTYEAR)
	SELECT @STATEMENTYEAR=@STATEMENTYEAR-1
END

IF @NUMPROPYEAR>=@MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL
BEGIN

	SELECT
	STATEMENTYEAR=#T0.STATEMENTYEAR,
	V=#T0.V,
	V1=#T0.V1,M1=(SELECT AVG(V1) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S1=(SELECT STDEV(V1) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V2=#T0.V2,M2=(SELECT AVG(V2) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S2=(SELECT STDEV(V2) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V3=#T0.V3,M3=(SELECT AVG(V3) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S3=(SELECT STDEV(V3) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V4=#T0.V4,M4=(SELECT AVG(V4) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S4=(SELECT STDEV(V4) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V5=#T0.V5,M5=(SELECT AVG(V5) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S5=(SELECT STDEV(V5) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V6=#T0.V6,M6=(SELECT AVG(V6) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S6=(SELECT STDEV(V6) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V7=#T0.V7,M7=(SELECT AVG(V7) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S7=(SELECT STDEV(V7) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V8=#T0.V8,M8=(SELECT AVG(V8) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S8=(SELECT STDEV(V8) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V9=#T0.V9,M9=(SELECT AVG(V9) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S9=(SELECT STDEV(V9) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V10=#T0.V10,M10=(SELECT AVG(V10) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S10=(SELECT STDEV(V10) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V11=#T0.V11,M11=(SELECT AVG(V11) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S11=(SELECT STDEV(V11) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V13=#T0.V13,M13=(SELECT AVG(V13) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S13=(SELECT STDEV(V13) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V15=#T0.V15,M15=(SELECT AVG(V15) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S15=(SELECT STDEV(V15) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V16=#T0.V16,M16=(SELECT AVG(V16) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S16=(SELECT STDEV(V16) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V17=#T0.V17,M17=(SELECT AVG(V17) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S17=(SELECT STDEV(V17) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V18=#T0.V18,M18=(SELECT AVG(V18) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S18=(SELECT STDEV(V18) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V19=#T0.V19,M19=(SELECT AVG(V19) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S19=(SELECT STDEV(V19) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V27=#T0.V27,M27=(SELECT AVG(V27) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S27=(SELECT STDEV(V27) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V29=#T0.V29,M29=(SELECT AVG(V29) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S29=(SELECT STDEV(V29) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V30=#T0.V30,M30=(SELECT AVG(V30) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S30=(SELECT STDEV(V30) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V31=#T0.V31,M31=(SELECT AVG(V31) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S31=(SELECT STDEV(V31) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V34=#T0.V34,M34=(SELECT AVG(V34) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S34=(SELECT STDEV(V34) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V35=#T0.V35,M35=(SELECT AVG(V35) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S35=(SELECT STDEV(V35) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V36=#T0.V36,M36=(SELECT AVG(V36) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S36=(SELECT STDEV(V36) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V38=#T0.V38,M38=(SELECT AVG(V38) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S38=(SELECT STDEV(V38) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	V39=#T0.V39,M39=(SELECT AVG(V39) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S39=(SELECT STDEV(V39) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR)

	--V20=#T0.V20,M20=(SELECT AVG(V20) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S20=(SELECT STDEV(V20) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V21=#T0.V21,M21=(SELECT AVG(V21) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S21=(SELECT STDEV(V21) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V40=#T0.V40,M40=(SELECT AVG(V40) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S40=(SELECT STDEV(V40) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V41=#T0.V41,M41=(SELECT AVG(V41) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S41=(SELECT STDEV(V41) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V42=#T0.V42,M42=(SELECT AVG(V42) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S42=(SELECT STDEV(V42) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),
	--V43=#T0.V43,M43=(SELECT AVG(V43) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR),S43=(SELECT STDEV(V43) FROM #T0 X WHERE X.STATEMENTYEAR=#T0.STATEMENTYEAR)

	INTO #T FROM #T0

	DROP TABLE #T0

	SELECT
	@NUMPROPERTIES=(SELECT COUNT(*) FROM #T),@MEAN0=(SELECT AVG(V) FROM #T),@SDV0=(SELECT STDEV(V) FROM #T)
	--INITIALIZE ALGORITHM
	SELECT 
	@RSQUARE=0,@STDERROR=0,
	@X1=0,@X2=0,@X3=0,@X4=0,@X5=0,@X6=0,@X7=0,@X8=0,@X9=0,@X10=0,@X11=0,@X12=0,@X13=0,@X14=0,@X15=0,@X16=0,@X17=0,@X18=0,@X19=0,@X20=0,@X21=0,@X22=0,@X23=0,@X24=0,@X25=0,@X26=0,@X27=0,@X28=0,@X29=0,@X30=0,@X31=0,@X32=0,@X33=0,@X34=0,@X35=0,@X36=0,@X37=0,@X38=0,@X39=0,@X40=0,@X41=0,@X42=0,@X43=0

	SELECT @NUM=0
	WHILE @NUM<=@NUMVAR AND @SDV0>0
	BEGIN

		SELECT 
		STATEMENTYEAR=T.STATEMENTYEAR,
		VN=T.V-@MEAN0
			-@X1*(V1-M1)*CASE WHEN S1>0 THEN (1/S1) ELSE 0 END
			-@X2*(V2-M2)*CASE WHEN S2>0 THEN (1/S2) ELSE 0 END
			-@X3*(V3-M3)*CASE WHEN S3>0 THEN (1/S3) ELSE 0 END
			-@X4*(V4-M4)*CASE WHEN S4>0 THEN (1/S4) ELSE 0 END
			-@X5*(V5-M5)*CASE WHEN S5>0 THEN (1/S5) ELSE 0 END
			-@X6*(V6-M6)*CASE WHEN S6>0 THEN (1/S6) ELSE 0 END
			-@X7*(V7-M7)*CASE WHEN S7>0 THEN (1/S7) ELSE 0 END
			-@X8*(V8-M8)*CASE WHEN S8>0 THEN (1/S8) ELSE 0 END
			-@X9*(V9-M9)*CASE WHEN S9>0 THEN (1/S9) ELSE 0 END
			-@X10*(V10-M10)*CASE WHEN S10>0 THEN (1/S10) ELSE 0 END
			-@X11*(V11-M11)*CASE WHEN S11>0 THEN (1/S11) ELSE 0 END
			-@X13*(V13-M13)*CASE WHEN S13>0 THEN (1/S13) ELSE 0 END
			-@X15*(V15-M15)*CASE WHEN S15>0 THEN (1/S15) ELSE 0 END
			-@X16*(V16-M16)*CASE WHEN S16>0 THEN (1/S16) ELSE 0 END
			---@X17*(V17-M17)*CASE WHEN S17>0 THEN (1/S17) ELSE 0 END
			---@X18*(V18-M18)*CASE WHEN S18>0 THEN (1/S18) ELSE 0 END
			---@X19*(V19-M19)*CASE WHEN S19>0 THEN (1/S19) ELSE 0 END
			---@X27*(V27-M27)*CASE WHEN S27>0 THEN (1/S27) ELSE 0 END
			---@X29*(V29-M29)*CASE WHEN S29>0 THEN (1/S29) ELSE 0 END
			---@X30*(V30-M30)*CASE WHEN S30>0 THEN (1/S30) ELSE 0 END
			---@X31*(V31-M31)*CASE WHEN S31>0 THEN (1/S31) ELSE 0 END
			---@X34*(V34-M34)*CASE WHEN S34>0 THEN (1/S34) ELSE 0 END
			-@X35*(V35-M35)*CASE WHEN S35>0 THEN (1/S35) ELSE 0 END
			---@X36*(V36-M36)*CASE WHEN S36>0 THEN (1/S36) ELSE 0 END
			---@X38*(V38-M38)*CASE WHEN S38>0 THEN (1/S38) ELSE 0 END
			-@X39*(V39-M39)*CASE WHEN S39>0 THEN (1/S39) ELSE 0 END,

			---@X20*(V20-M20)*CASE WHEN S20>0 THEN (1/S20) ELSE 0 END
			---@X21*(V21-M21)*CASE WHEN S21>0 THEN (1/S21) ELSE 0 END
			---@X40*(V40-M40)*CASE WHEN S40>0 THEN (1/S40) ELSE 0 END
			---@X41*(V41-M41)*CASE WHEN S41>0 THEN (1/S41) ELSE 0 END
			---@X42*(V42-M42)*CASE WHEN S42>0 THEN (1/S42) ELSE 0 END
			---@X43*(V43-M43)*CASE WHEN S43>0 THEN (1/S43) ELSE 0 END,


		V=T.V,
		V1=T.V1,M1=T.M1,S1=T.S1,
		V2=T.V2,M2=T.M2,S2=T.S2,
		V3=T.V3,M3=T.M3,S3=T.S3,
		V4=T.V4,M4=T.M4,S4=T.S4,
		V5=T.V5,M5=T.M5,S5=T.S5,
		V6=T.V6,M6=T.M6,S6=T.S6,
		V7=T.V7,M7=T.M7,S7=T.S7,
		V8=T.V8,M8=T.M8,S8=T.S8,
		V9=T.V9,M9=T.M9,S9=T.S9,
		V10=T.V10,M10=T.M10,S10=T.S10,
		V11=T.V11,M11=T.M11,S11=T.S11,
		V13=T.V13,M13=T.M13,S13=T.S13,
		V15=T.V15,M15=T.M15,S15=T.S15,
		V16=T.V16,M16=T.M16,S16=T.S16,
		--V17=T.V17,M17=T.M17,S17=T.S17,
		--V18=T.V18,M18=T.M18,S18=T.S18,
		--V19=T.V19,M19=T.M19,S19=T.S19,
		--V27=T.V27,M27=T.M27,S27=T.S27,
		--V29=T.V29,M29=T.M29,S29=T.S29,
		--V30=T.V30,M30=T.M30,S30=T.S30,
		--V31=T.V31,M31=T.M31,S31=T.S31,
		--V34=T.V34,M34=T.M34,S34=T.S34,
		V35=T.V35,M35=T.M35,S35=T.S35,
		--V36=T.V36,M36=T.M36,S36=T.S36,
		--V38=T.V38,M38=T.M38,S38=T.S38,
		V39=T.V39,M39=T.M39,S39=T.S39

		--V20=T.V20,M20=T.M20,S20=T.S20,
		--V21=T.V21,M21=T.M21,S21=T.S21,
		--V40=T.V40,M40=T.M40,S40=T.S40,
		--V41=T.V41,M41=T.M41,S41=T.S41,
		--V42=T.V42,M42=T.M42,S42=T.S42,
		--V43=T.V43,M43=T.M43,S43=T.S43

		INTO #TN FROM #T T

		SELECT @SDV=(SELECT STDEV(VN) FROM #TN)

		SELECT @STDERROR=@SDV
		SELECT @RSQUARE=(1-(@STDERROR*@STDERROR/(@SDV0*@SDV0)))

		IF @NUM=1 AND @STDERROR>0 SELECT @I1=@I,@STDERROR1=@STDERROR,@RSQUARE1=@RSQUARE
		ELSE IF @NUM=2 AND @STDERROR>0 BEGIN SELECT @I2=@I,@STDERROR2=@STDERROR SELECT @RSQUARE2=(1-(@STDERROR2*@STDERROR2/(@STDERROR1*@STDERROR1))) END
		ELSE IF @NUM=3 AND @STDERROR>0 BEGIN SELECT @I3=@I,@STDERROR3=@STDERROR SELECT @RSQUARE3=(1-(@STDERROR3*@STDERROR3/(@STDERROR2*@STDERROR2))) END
		ELSE IF @NUM=4 AND @STDERROR>0 BEGIN SELECT @I4=@I,@STDERROR4=@STDERROR SELECT @RSQUARE4=(1-(@STDERROR4*@STDERROR4/(@STDERROR3*@STDERROR3))) END
		ELSE IF @NUM=5 AND @STDERROR>0 BEGIN SELECT @I5=@I,@STDERROR5=@STDERROR SELECT @RSQUARE5=(1-(@STDERROR5*@STDERROR5/(@STDERROR4*@STDERROR4))) END

		SELECT @NUM=@NUM+1

		SELECT 
		@C1=(SELECT AVG(VN*(V1-M1)*CASE WHEN @SDV*S1>0 THEN 1/(@SDV*S1) ELSE 0 END) FROM #TN),
		@C2=(SELECT AVG(VN*(V2-M2)*CASE WHEN @SDV*S2>0 THEN 1/(@SDV*S2) ELSE 0 END) FROM #TN),
		@C3=(SELECT AVG(VN*(V3-M3)*CASE WHEN @SDV*S3>0 THEN 1/(@SDV*S3) ELSE 0 END) FROM #TN),
		@C4=(SELECT AVG(VN*(V4-M4)*CASE WHEN @SDV*S4>0 THEN 1/(@SDV*S4) ELSE 0 END) FROM #TN),
		@C5=(SELECT AVG(VN*(V5-M5)*CASE WHEN @SDV*S5>0 THEN 1/(@SDV*S5) ELSE 0 END) FROM #TN),
		@C6=(SELECT AVG(VN*(V6-M6)*CASE WHEN @SDV*S6>0 THEN 1/(@SDV*S6) ELSE 0 END) FROM #TN),
		@C7=(SELECT AVG(VN*(V7-M7)*CASE WHEN @SDV*S7>0 THEN 1/(@SDV*S7) ELSE 0 END) FROM #TN),
		@C8=(SELECT AVG(VN*(V8-M8)*CASE WHEN @SDV*S8>0 THEN 1/(@SDV*S8) ELSE 0 END) FROM #TN),
		@C9=(SELECT AVG(VN*(V9-M9)*CASE WHEN @SDV*S9>0 THEN 1/(@SDV*S9) ELSE 0 END) FROM #TN),
		@C10=(SELECT AVG(VN*(V10-M10)*CASE WHEN @SDV*S10>0 THEN 1/(@SDV*S10) ELSE 0 END) FROM #TN),
		@C11=(SELECT AVG(VN*(V11-M11)*CASE WHEN @SDV*S11>0 THEN 1/(@SDV*S11) ELSE 0 END) FROM #TN),
		@C13=(SELECT AVG(VN*(V13-M13)*CASE WHEN @SDV*S13>0 THEN 1/(@SDV*S13) ELSE 0 END) FROM #TN),
		@C15=(SELECT AVG(VN*(V15-M15)*CASE WHEN @SDV*S15>0 THEN 1/(@SDV*S15) ELSE 0 END) FROM #TN),
		@C16=(SELECT AVG(VN*(V16-M16)*CASE WHEN @SDV*S16>0 THEN 1/(@SDV*S16) ELSE 0 END) FROM #TN),
		--@C17=(SELECT AVG(VN*(V17-M17)*CASE WHEN @SDV*S17>0 THEN 1/(@SDV*S17) ELSE 0 END) FROM #TN),
		--@C18=(SELECT AVG(VN*(V18-M18)*CASE WHEN @SDV*S18>0 THEN 1/(@SDV*S18) ELSE 0 END) FROM #TN),
		--@C19=(SELECT AVG(VN*(V19-M19)*CASE WHEN @SDV*S19>0 THEN 1/(@SDV*S19) ELSE 0 END) FROM #TN),
		--@C27=(SELECT AVG(VN*(V27-M27)*CASE WHEN @SDV*S27>0 THEN 1/(@SDV*S27) ELSE 0 END) FROM #TN),
		--@C29=(SELECT AVG(VN*(V29-M29)*CASE WHEN @SDV*S29>0 THEN 1/(@SDV*S29) ELSE 0 END) FROM #TN),
		--@C30=(SELECT AVG(VN*(V30-M30)*CASE WHEN @SDV*S30>0 THEN 1/(@SDV*S30) ELSE 0 END) FROM #TN),
		--@C31=(SELECT AVG(VN*(V31-M31)*CASE WHEN @SDV*S31>0 THEN 1/(@SDV*S31) ELSE 0 END) FROM #TN),
		--@C34=(SELECT AVG(VN*(V34-M34)*CASE WHEN @SDV*S34>0 THEN 1/(@SDV*S34) ELSE 0 END) FROM #TN),
		@C35=(SELECT AVG(VN*(V35-M35)*CASE WHEN @SDV*S35>0 THEN 1/(@SDV*S35) ELSE 0 END) FROM #TN),
		--@C36=(SELECT AVG(VN*(V36-M36)*CASE WHEN @SDV*S36>0 THEN 1/(@SDV*S36) ELSE 0 END) FROM #TN),
		--@C38=(SELECT AVG(VN*(V38-M38)*CASE WHEN @SDV*S38>0 THEN 1/(@SDV*S38) ELSE 0 END) FROM #TN),
		@C39=(SELECT AVG(VN*(V39-M39)*CASE WHEN @SDV*S39>0 THEN 1/(@SDV*S39) ELSE 0 END) FROM #TN)

		--@C20=(SELECT AVG(VN*(V20-M20)*CASE WHEN @SDV*S20>0 THEN 1/(@SDV*S20) ELSE 0 END) FROM #TN),
		--@C21=(SELECT AVG(VN*(V21-M21)*CASE WHEN @SDV*S21>0 THEN 1/(@SDV*S21) ELSE 0 END) FROM #TN),
		--@C40=(SELECT AVG(VN*(V40-M40)*CASE WHEN @SDV*S40>0 THEN 1/(@SDV*S40) ELSE 0 END) FROM #TN),
		--@C41=(SELECT AVG(VN*(V41-M41)*CASE WHEN @SDV*S41>0 THEN 1/(@SDV*S41) ELSE 0 END) FROM #TN),
		--@C42=(SELECT AVG(VN*(V42-M42)*CASE WHEN @SDV*S42>0 THEN 1/(@SDV*S42) ELSE 0 END) FROM #TN),
		--@C43=(SELECT AVG(VN*(V43-M43)*CASE WHEN @SDV*S43>0 THEN 1/(@SDV*S43) ELSE 0 END) FROM #TN)

		IF @NUM=1 
		SELECT
		@CORREL1=@C1,
		@CORREL2=@C2,
		@CORREL3=@C3,
		@CORREL4=@C4,
		@CORREL5=@C5,
		@CORREL6=@C6,
		@CORREL7=@C7,
		@CORREL8=@C8,
		@CORREL9=@C9,
		@CORREL10=@C10,
		@CORREL11=@C11,
		@CORREL13=@C13,
		@CORREL15=@C15,
		@CORREL16=@C16,
		--@CORREL17=@C17,
		--@CORREL18=@C18,
		--@CORREL19=@C19,
		--@CORREL27=@C27,
		--@CORREL29=@C29,
		--@CORREL30=@C30,
		--@CORREL31=@C31,
		--@CORREL34=@C34,
		@CORREL35=@C35,
		--@CORREL36=@C36,
		--@CORREL38=@C38,
		@CORREL39=@C39

		--@CORREL20=@C20,
		--@CORREL21=@C21,
		--@CORREL40=@C40,
		--@CORREL41=@C41,
		--@CORREL42=@C42,
		--@CORREL43=@C43

		DROP TABLE #TN

		SELECT @MAXCORREL=0,@I=0
		IF ABS(@C1)>ABS(@MAXCORREL) AND @C1*@CORREL1>0 SELECT @MAXCORREL=@C1,@I=1
		IF ABS(@C2)>ABS(@MAXCORREL) AND @C2*@CORREL2>0 SELECT @MAXCORREL=@C2,@I=2
		IF ABS(@C3)>ABS(@MAXCORREL) AND @C3*@CORREL3>0 SELECT @MAXCORREL=@C3,@I=3
		IF ABS(@C4)>ABS(@MAXCORREL) AND @C4*@CORREL4>0 SELECT @MAXCORREL=@C4,@I=4
		IF ABS(@C5)>ABS(@MAXCORREL) AND @C5*@CORREL5>0 SELECT @MAXCORREL=@C5,@I=5
		IF ABS(@C6)>ABS(@MAXCORREL) AND @C6*@CORREL6>0 SELECT @MAXCORREL=@C6,@I=6
		IF ABS(@C7)>ABS(@MAXCORREL) AND @C7*@CORREL7>0 SELECT @MAXCORREL=@C7,@I=7
		IF ABS(@C8)>ABS(@MAXCORREL) AND @C8*@CORREL8>0 SELECT @MAXCORREL=@C8,@I=8
		IF ABS(@C9)>ABS(@MAXCORREL) AND @C9*@CORREL9>0 SELECT @MAXCORREL=@C9,@I=9
		IF ABS(@C10)>ABS(@MAXCORREL) AND @C10*@CORREL10>0 SELECT @MAXCORREL=@C10,@I=10
		IF ABS(@C11)>ABS(@MAXCORREL) AND @C11*@CORREL11>0 SELECT @MAXCORREL=@C11,@I=11
		IF ABS(@C13)>ABS(@MAXCORREL) AND @C13*@CORREL13>0 SELECT @MAXCORREL=@C13,@I=13
		IF ABS(@C15)>ABS(@MAXCORREL) AND @C15*@CORREL15>0 SELECT @MAXCORREL=@C15,@I=15
		IF ABS(@C16)>ABS(@MAXCORREL) AND @C16*@CORREL16>0 SELECT @MAXCORREL=@C16,@I=16
		--IF ABS(@C17)>ABS(@MAXCORREL) AND @C17*@CORREL17>0 SELECT @MAXCORREL=@C17,@I=17
		--IF ABS(@C18)>ABS(@MAXCORREL) AND @C18*@CORREL18>0 SELECT @MAXCORREL=@C18,@I=18
		--IF ABS(@C19)>ABS(@MAXCORREL) AND @C19*@CORREL19>0 SELECT @MAXCORREL=@C19,@I=19
		--IF ABS(@C27)>ABS(@MAXCORREL) AND @C27*@CORREL27>0 SELECT @MAXCORREL=@C27,@I=27
		--IF ABS(@C29)>ABS(@MAXCORREL) AND @C29*@CORREL29>0 SELECT @MAXCORREL=@C29,@I=29
		--IF ABS(@C30)>ABS(@MAXCORREL) AND @C30*@CORREL30>0 SELECT @MAXCORREL=@C30,@I=30
		--IF ABS(@C31)>ABS(@MAXCORREL) AND @C31*@CORREL31>0 SELECT @MAXCORREL=@C31,@I=31
		--IF ABS(@C34)>ABS(@MAXCORREL) AND @C34*@CORREL34>0 SELECT @MAXCORREL=@C34,@I=34
		IF ABS(@C35)>ABS(@MAXCORREL) AND @C35*@CORREL35>0 SELECT @MAXCORREL=@C35,@I=35
		--IF ABS(@C36)>ABS(@MAXCORREL) AND @C36*@CORREL36>0 SELECT @MAXCORREL=@C36,@I=36
		--IF ABS(@C38)>ABS(@MAXCORREL) AND @C38*@CORREL38>0 SELECT @MAXCORREL=@C38,@I=38
		IF ABS(@C39)>ABS(@MAXCORREL) AND @C39*@CORREL39>0 SELECT @MAXCORREL=@C39,@I=39

		--IF ABS(@C20)>ABS(@MAXCORREL) AND @C20*@CORREL20>0 SELECT @MAXCORREL=@C20,@I=20
		--IF ABS(@C21)>ABS(@MAXCORREL) AND @C21*@CORREL21>0 SELECT @MAXCORREL=@C21,@I=21
		--IF ABS(@C40)>ABS(@MAXCORREL) AND @C40*@CORREL40>0 SELECT @MAXCORREL=@C40,@I=40
		--IF ABS(@C41)>ABS(@MAXCORREL) AND @C41*@CORREL41>0 SELECT @MAXCORREL=@C41,@I=41
		--IF ABS(@C42)>ABS(@MAXCORREL) AND @C42*@CORREL42>0 SELECT @MAXCORREL=@C42,@I=42
		--IF ABS(@C43)>ABS(@MAXCORREL) AND @C43*@CORREL43>0 SELECT @MAXCORREL=@C43,@I=43

		IF @I=1 SELECT @X1=@MAXCORREL*@SDV 
		ELSE IF @I=2 SELECT @X2=@MAXCORREL*@SDV 
		ELSE IF @I=3 SELECT @X3=@MAXCORREL*@SDV 
		ELSE IF @I=4 SELECT @X4=@MAXCORREL*@SDV 
		ELSE IF @I=5 SELECT @X5=@MAXCORREL*@SDV 
		ELSE IF @I=6 SELECT @X6=@MAXCORREL*@SDV 
		ELSE IF @I=7 SELECT @X7=@MAXCORREL*@SDV 
		ELSE IF @I=8 SELECT @X8=@MAXCORREL*@SDV 
		ELSE IF @I=9 SELECT @X9=@MAXCORREL*@SDV 
		ELSE IF @I=10 SELECT @X10=@MAXCORREL*@SDV 
		ELSE IF @I=11 SELECT @X11=@MAXCORREL*@SDV 
		ELSE IF @I=13 SELECT @X13=@MAXCORREL*@SDV 
		ELSE IF @I=15 SELECT @X15=@MAXCORREL*@SDV 
		ELSE IF @I=16 SELECT @X16=@MAXCORREL*@SDV 
		--ELSE IF @I=17 SELECT @X17=@MAXCORREL*@SDV 
		--ELSE IF @I=18 SELECT @X18=@MAXCORREL*@SDV 
		--ELSE IF @I=19 SELECT @X19=@MAXCORREL*@SDV 
		--ELSE IF @I=27 SELECT @X27=@MAXCORREL*@SDV 
		--ELSE IF @I=29 SELECT @X29=@MAXCORREL*@SDV 
		--ELSE IF @I=30 SELECT @X30=@MAXCORREL*@SDV 
		--ELSE IF @I=31 SELECT @X31=@MAXCORREL*@SDV 
		--ELSE IF @I=34 SELECT @X34=@MAXCORREL*@SDV 
		ELSE IF @I=35 SELECT @X35=@MAXCORREL*@SDV 
		--ELSE IF @I=36 SELECT @X36=@MAXCORREL*@SDV 
		--ELSE IF @I=38 SELECT @X38=@MAXCORREL*@SDV
		ELSE IF @I=39 SELECT @X39=@MAXCORREL*@SDV 
		
		--ELSE IF @I=20 SELECT @X20=@MAXCORREL*@SDV 
		--ELSE IF @I=21 SELECT @X21=@MAXCORREL*@SDV 
		--ELSE IF @I=40 SELECT @X40=@MAXCORREL*@SDV 
		--ELSE IF @I=41 SELECT @X41=@MAXCORREL*@SDV 
		--ELSE IF @I=42 SELECT @X42=@MAXCORREL*@SDV
		--ELSE IF @I=43 SELECT @X43=@MAXCORREL*@SDV  

IF @I1=1 SELECT @VAR1='YearBuiltRenov',@COEFF1=@X1 ,@MEAN1=(SELECT AVG(M1) FROM #T),@SDV1=(SELECT AVG(S1) FROM #T)  
ELSE IF @I1=2 SELECT @VAR1='PopulationPerSqMile',@COEFF1=@X2 ,@MEAN1=(SELECT AVG(M2) FROM #T),@SDV1=(SELECT AVG(S2) FROM #T)  
ELSE IF @I1=3 SELECT @VAR1='MedianHHInc',@COEFF1=@X3 ,@MEAN1=(SELECT AVG(M3) FROM #T),@SDV1=(SELECT AVG(S3) FROM #T)  
ELSE IF @I1=4 SELECT @VAR1='MedianHomeVal',@COEFF1=@X4 ,@MEAN1=(SELECT AVG(M4) FROM #T),@SDV1=(SELECT AVG(S4) FROM #T)  
ELSE IF @I1=5 SELECT @VAR1='Median_Rent',@COEFF1=@X5 ,@MEAN1=(SELECT AVG(M5) FROM #T),@SDV1=(SELECT AVG(S5) FROM #T)  
ELSE IF @I1=6 SELECT @VAR1='MedianAge',@COEFF1=@X6 ,@MEAN1=(SELECT AVG(M6) FROM #T),@SDV1=(SELECT AVG(S6) FROM #T)  
ELSE IF @I1=7 SELECT @VAR1='Median_Owner_Costs',@COEFF1=@X7 ,@MEAN1=(SELECT AVG(M7) FROM #T),@SDV1=(SELECT AVG(S7) FROM #T)  
ELSE IF @I1=8 SELECT @VAR1='RenterPCT',@COEFF1=@X8 ,@MEAN1=(SELECT AVG(M8) FROM #T),@SDV1=(SELECT AVG(S8) FROM #T)  
ELSE IF @I1=9 SELECT @VAR1='CashRentOver30PCT',@COEFF1=@X9 ,@MEAN1=(SELECT AVG(M9) FROM #T),@SDV1=(SELECT AVG(S9) FROM #T)  
ELSE IF @I1=10 SELECT @VAR1='BachelorsOrMorePCT',@COEFF1=@X10 ,@MEAN1=(SELECT AVG(M10) FROM #T),@SDV1=(SELECT AVG(S10) FROM #T)  
ELSE IF @I1=11 SELECT @VAR1='UnemploymentPCT',@COEFF1=@X11 ,@MEAN1=(SELECT AVG(M11) FROM #T),@SDV1=(SELECT AVG(S11) FROM #T)  
ELSE IF @I1=13 SELECT @VAR1='MngtFinancePCT',@COEFF1=@X13 ,@MEAN1=(SELECT AVG(M13) FROM #T),@SDV1=(SELECT AVG(S13) FROM #T)  
ELSE IF @I1=15 SELECT @VAR1='MovedIn2010orLaterPCT',@COEFF1=@X15 ,@MEAN1=(SELECT AVG(M15) FROM #T),@SDV1=(SELECT AVG(S15) FROM #T)  
ELSE IF @I1=16 SELECT @VAR1='HPI_1YRCH',@COEFF1=@X16 ,@MEAN1=(SELECT AVG(M16) FROM #T),@SDV1=(SELECT AVG(S16) FROM #T)  
--ELSE IF @I1=17 SELECT @VAR1='OCCUP',@COEFF1=@X17 ,@MEAN1=(SELECT AVG(M17) FROM #T),@SDV1=(SELECT AVG(S17) FROM #T)  
--ELSE IF @I1=18 SELECT @VAR1='REV_PERUNIT',@COEFF1=@X18,@MEAN1=(SELECT AVG(M18) FROM #T),@SDV1=(SELECT AVG(S18) FROM #T)  
--ELSE IF @I1=19 SELECT @VAR1='EXP_PCTREV',@COEFF1=@X19,@MEAN1=(SELECT AVG(M19) FROM #T),@SDV1=(SELECT AVG(S19) FROM #T)  
--ELSE IF @I1=27 SELECT @VAR1='CAPEX0_PCTREV',@COEFF1=@X27,@MEAN1=(SELECT AVG(M27) FROM #T),@SDV1=(SELECT AVG(S27) FROM #T)  
--ELSE IF @I1=29 SELECT @VAR1='OCCUP_1YRCH',@COEFF1=@X29,@MEAN1=(SELECT AVG(M29) FROM #T),@SDV1=(SELECT AVG(S29) FROM #T)  
--ELSE IF @I1=30 SELECT @VAR1='REV_1YR_PCT_CH',@COEFF1=@X30 ,@MEAN1=(SELECT AVG(M30) FROM #T),@SDV1=(SELECT AVG(S30) FROM #T)  
--ELSE IF @I1=31 SELECT @VAR1='EXP_1YR_PCT_CH',@COEFF1=@X31,@MEAN1=(SELECT AVG(M31) FROM #T),@SDV1=(SELECT AVG(S31) FROM #T)  
--ELSE IF @I1=34 SELECT @VAR1='YearBuilt',@COEFF1=@X34,@MEAN1=(SELECT AVG(M34) FROM #T),@SDV1=(SELECT AVG(S34) FROM #T)  
ELSE IF @I1=35 SELECT @VAR1='NumUnits',@COEFF1=@X35,@MEAN1=(SELECT AVG(M35) FROM #T),@SDV1=(SELECT AVG(S35) FROM #T)  
--ELSE IF @I1=36 SELECT @VAR1='RevenuePctMedianIncome',@COEFF1=@X36,@MEAN1=(SELECT AVG(M36) FROM #T),@SDV1=(SELECT AVG(S36) FROM #T)  
--ELSE IF @I1=38 SELECT @VAR1='NOI_1YR_PCT_CH',@COEFF1=@X38,@MEAN1=(SELECT AVG(M38) FROM #T),@SDV1=(SELECT AVG(S38) FROM #T)  
ELSE IF @I1=39 SELECT @VAR1='HPI_METRO_1YRCH',@COEFF1=@X39,@MEAN1=(SELECT AVG(M39) FROM #T),@SDV1=(SELECT AVG(S39) FROM #T)  

--ELSE IF @I1=20 SELECT @VAR1='RETAXES_PCTREV',@COEFF1=@X20,@MEAN1=(SELECT AVG(M20) FROM #T),@SDV1=(SELECT AVG(S20) FROM #T)  
--ELSE IF @I1=21 SELECT @VAR1='PROPINS_PCTREV',@COEFF1=@X21,@MEAN1=(SELECT AVG(M21) FROM #T),@SDV1=(SELECT AVG(S21) FROM #T)  
--ELSE IF @I1=40 SELECT @VAR1='UTILITI_PCTREV',@COEFF1=@X40,@MEAN1=(SELECT AVG(M40) FROM #T),@SDV1=(SELECT AVG(S40) FROM #T)  
--ELSE IF @I1=41 SELECT @VAR1='REPAIRS_PCTREV',@COEFF1=@X41,@MEAN1=(SELECT AVG(M41) FROM #T),@SDV1=(SELECT AVG(S41) FROM #T)  
--ELSE IF @I1=42 SELECT @VAR1='MANAGEM_PCTREV',@COEFF1=@X42,@MEAN1=(SELECT AVG(M42) FROM #T),@SDV1=(SELECT AVG(S42) FROM #T)  
--ELSE IF @I1=43 SELECT @VAR1='PAYROLL_PCTREV',@COEFF1=@X43,@MEAN1=(SELECT AVG(M43) FROM #T),@SDV1=(SELECT AVG(S43) FROM #T)  


IF @I2=1 SELECT @VAR2='YearBuiltRenov',@COEFF2=@X1 ,@MEAN2=(SELECT AVG(M1) FROM #T),@SDV2=(SELECT AVG(S1) FROM #T)  
ELSE IF @I2=2 SELECT @VAR2='PopulationPerSqMile',@COEFF2=@X2 ,@MEAN2=(SELECT AVG(M2) FROM #T),@SDV2=(SELECT AVG(S2) FROM #T)  
ELSE IF @I2=3 SELECT @VAR2='MedianHHInc',@COEFF2=@X3 ,@MEAN2=(SELECT AVG(M3) FROM #T),@SDV2=(SELECT AVG(S3) FROM #T)  
ELSE IF @I2=4 SELECT @VAR2='MedianHomeVal',@COEFF2=@X4 ,@MEAN2=(SELECT AVG(M4) FROM #T),@SDV2=(SELECT AVG(S4) FROM #T)  
ELSE IF @I2=5 SELECT @VAR2='Median_Rent',@COEFF2=@X5 ,@MEAN2=(SELECT AVG(M5) FROM #T),@SDV2=(SELECT AVG(S5) FROM #T)  
ELSE IF @I2=6 SELECT @VAR2='MedianAge',@COEFF2=@X6 ,@MEAN2=(SELECT AVG(M6) FROM #T),@SDV2=(SELECT AVG(S6) FROM #T)  
ELSE IF @I2=7 SELECT @VAR2='Median_Owner_Costs',@COEFF2=@X7 ,@MEAN2=(SELECT AVG(M7) FROM #T),@SDV2=(SELECT AVG(S7) FROM #T)  
ELSE IF @I2=8 SELECT @VAR2='RenterPCT',@COEFF2=@X8 ,@MEAN2=(SELECT AVG(M8) FROM #T),@SDV2=(SELECT AVG(S8) FROM #T)  
ELSE IF @I2=9 SELECT @VAR2='CashRentOver30PCT',@COEFF2=@X9 ,@MEAN2=(SELECT AVG(M9) FROM #T),@SDV2=(SELECT AVG(S9) FROM #T)  
ELSE IF @I2=10 SELECT @VAR2='BachelorsOrMorePCT',@COEFF2=@X10 ,@MEAN2=(SELECT AVG(M10) FROM #T),@SDV2=(SELECT AVG(S10) FROM #T)  
ELSE IF @I2=11 SELECT @VAR2='UnemploymentPCT',@COEFF2=@X11 ,@MEAN2=(SELECT AVG(M11) FROM #T),@SDV2=(SELECT AVG(S11) FROM #T)  
ELSE IF @I2=13 SELECT @VAR2='MngtFinancePCT',@COEFF2=@X13 ,@MEAN2=(SELECT AVG(M13) FROM #T),@SDV2=(SELECT AVG(S13) FROM #T)  
ELSE IF @I2=15 SELECT @VAR2='MovedIn2010orLaterPCT',@COEFF2=@X15 ,@MEAN2=(SELECT AVG(M15) FROM #T),@SDV2=(SELECT AVG(S15) FROM #T)  
ELSE IF @I2=16 SELECT @VAR2='HPI_1YRCH',@COEFF2=@X16 ,@MEAN2=(SELECT AVG(M16) FROM #T),@SDV2=(SELECT AVG(S16) FROM #T)  
--ELSE IF @I2=17 SELECT @VAR2='OCCUP',@COEFF2=@X17 ,@MEAN2=(SELECT AVG(M17) FROM #T),@SDV2=(SELECT AVG(S17) FROM #T)  
--ELSE IF @I2=18 SELECT @VAR2='REV_PERUNIT',@COEFF2=@X18,@MEAN2=(SELECT AVG(M18) FROM #T),@SDV2=(SELECT AVG(S18) FROM #T)  
--ELSE IF @I2=19 SELECT @VAR2='EXP_PCTREV',@COEFF2=@X19,@MEAN2=(SELECT AVG(M19) FROM #T),@SDV2=(SELECT AVG(S19) FROM #T)  
--ELSE IF @I2=27 SELECT @VAR2='CAPEX0_PCTREV',@COEFF2=@X27,@MEAN2=(SELECT AVG(M27) FROM #T),@SDV2=(SELECT AVG(S27) FROM #T)  
--ELSE IF @I2=29 SELECT @VAR2='OCCUP_1YRCH',@COEFF2=@X29,@MEAN2=(SELECT AVG(M29) FROM #T),@SDV2=(SELECT AVG(S29) FROM #T)  
--ELSE IF @I2=30 SELECT @VAR2='REV_1YR_PCT_CH',@COEFF2=@X30 ,@MEAN2=(SELECT AVG(M30) FROM #T),@SDV2=(SELECT AVG(S30) FROM #T)  
--ELSE IF @I2=31 SELECT @VAR2='EXP_1YR_PCT_CH',@COEFF2=@X31,@MEAN2=(SELECT AVG(M31) FROM #T),@SDV2=(SELECT AVG(S31) FROM #T)  
--ELSE IF @I2=34 SELECT @VAR2='YearBuilt',@COEFF2=@X34,@MEAN2=(SELECT AVG(M34) FROM #T),@SDV2=(SELECT AVG(S34) FROM #T)  
ELSE IF @I2=35 SELECT @VAR2='NumUnits',@COEFF2=@X35,@MEAN2=(SELECT AVG(M35) FROM #T),@SDV2=(SELECT AVG(S35) FROM #T)  
--ELSE IF @I2=36 SELECT @VAR2='RevenuePctMedianIncome',@COEFF2=@X36,@MEAN2=(SELECT AVG(M36) FROM #T),@SDV2=(SELECT AVG(S36) FROM #T)  
--ELSE IF @I2=38 SELECT @VAR2='NOI_1YR_PCT_CH',@COEFF2=@X38,@MEAN2=(SELECT AVG(M38) FROM #T),@SDV2=(SELECT AVG(S38) FROM #T)  
ELSE IF @I2=39 SELECT @VAR2='HPI_METRO_1YRCH',@COEFF2=@X39,@MEAN2=(SELECT AVG(M39) FROM #T),@SDV2=(SELECT AVG(S39) FROM #T)  

--ELSE IF @I2=20 SELECT @VAR2='RETAXES_PCTREV',@COEFF2=@X20,@MEAN2=(SELECT AVG(M20) FROM #T),@SDV2=(SELECT AVG(S20) FROM #T)  
--ELSE IF @I2=21 SELECT @VAR2='PROPINS_PCTREV',@COEFF2=@X21,@MEAN2=(SELECT AVG(M21) FROM #T),@SDV2=(SELECT AVG(S21) FROM #T)  
--ELSE IF @I2=40 SELECT @VAR2='UTILITI_PCTREV',@COEFF2=@X40,@MEAN2=(SELECT AVG(M40) FROM #T),@SDV2=(SELECT AVG(S40) FROM #T)  
--ELSE IF @I2=41 SELECT @VAR2='REPAIRS_PCTREV',@COEFF2=@X41,@MEAN2=(SELECT AVG(M41) FROM #T),@SDV2=(SELECT AVG(S41) FROM #T)  
--ELSE IF @I2=42 SELECT @VAR2='MANAGEM_PCTREV',@COEFF2=@X42,@MEAN2=(SELECT AVG(M42) FROM #T),@SDV2=(SELECT AVG(S42) FROM #T)  
--ELSE IF @I2=43 SELECT @VAR2='PAYROLL_PCTREV',@COEFF2=@X43,@MEAN2=(SELECT AVG(M43) FROM #T),@SDV2=(SELECT AVG(S43) FROM #T)  

IF @I3=1 SELECT @VAR3='YearBuiltRenov',@COEFF3=@X1 ,@MEAN3=(SELECT AVG(M1) FROM #T),@SDV3=(SELECT AVG(S1) FROM #T)  
ELSE IF @I3=2 SELECT @VAR3='PopulationPerSqMile',@COEFF3=@X2 ,@MEAN3=(SELECT AVG(M2) FROM #T),@SDV3=(SELECT AVG(S2) FROM #T)  
ELSE IF @I3=3 SELECT @VAR3='MedianHHInc',@COEFF3=@X3 ,@MEAN3=(SELECT AVG(M3) FROM #T),@SDV3=(SELECT AVG(S3) FROM #T)  
ELSE IF @I3=4 SELECT @VAR3='MedianHomeVal',@COEFF3=@X4 ,@MEAN3=(SELECT AVG(M4) FROM #T),@SDV3=(SELECT AVG(S4) FROM #T)  
ELSE IF @I3=5 SELECT @VAR3='Median_Rent',@COEFF3=@X5 ,@MEAN3=(SELECT AVG(M5) FROM #T),@SDV3=(SELECT AVG(S5) FROM #T)  
ELSE IF @I3=6 SELECT @VAR3='MedianAge',@COEFF3=@X6 ,@MEAN3=(SELECT AVG(M6) FROM #T),@SDV3=(SELECT AVG(S6) FROM #T)  
ELSE IF @I3=7 SELECT @VAR3='Median_Owner_Costs',@COEFF3=@X7 ,@MEAN3=(SELECT AVG(M7) FROM #T),@SDV3=(SELECT AVG(S7) FROM #T)  
ELSE IF @I3=8 SELECT @VAR3='RenterPCT',@COEFF3=@X8 ,@MEAN3=(SELECT AVG(M8) FROM #T),@SDV3=(SELECT AVG(S8) FROM #T)  
ELSE IF @I3=9 SELECT @VAR3='CashRentOver30PCT',@COEFF3=@X9 ,@MEAN3=(SELECT AVG(M9) FROM #T),@SDV3=(SELECT AVG(S9) FROM #T)  
ELSE IF @I3=10 SELECT @VAR3='BachelorsOrMorePCT',@COEFF3=@X10 ,@MEAN3=(SELECT AVG(M10) FROM #T),@SDV3=(SELECT AVG(S10) FROM #T)  
ELSE IF @I3=11 SELECT @VAR3='UnemploymentPCT',@COEFF3=@X11 ,@MEAN3=(SELECT AVG(M11) FROM #T),@SDV3=(SELECT AVG(S11) FROM #T)  
ELSE IF @I3=13 SELECT @VAR3='MngtFinancePCT',@COEFF3=@X13 ,@MEAN3=(SELECT AVG(M13) FROM #T),@SDV3=(SELECT AVG(S13) FROM #T)  
ELSE IF @I3=15 SELECT @VAR3='MovedIn2010orLaterPCT',@COEFF3=@X15 ,@MEAN3=(SELECT AVG(M15) FROM #T),@SDV3=(SELECT AVG(S15) FROM #T)  
ELSE IF @I3=16 SELECT @VAR3='HPI_1YRCH',@COEFF3=@X16 ,@MEAN3=(SELECT AVG(M16) FROM #T),@SDV3=(SELECT AVG(S16) FROM #T)  
--ELSE IF @I3=17 SELECT @VAR3='OCCUP',@COEFF3=@X17 ,@MEAN3=(SELECT AVG(M17) FROM #T),@SDV3=(SELECT AVG(S17) FROM #T)  
--ELSE IF @I3=18 SELECT @VAR3='REV_PERUNIT',@COEFF3=@X18,@MEAN3=(SELECT AVG(M18) FROM #T),@SDV3=(SELECT AVG(S18) FROM #T)  
--ELSE IF @I3=19 SELECT @VAR3='EXP_PCTREV',@COEFF3=@X19,@MEAN3=(SELECT AVG(M19) FROM #T),@SDV3=(SELECT AVG(S19) FROM #T)  
--ELSE IF @I3=27 SELECT @VAR3='CAPEX0_PCTREV',@COEFF3=@X27,@MEAN3=(SELECT AVG(M27) FROM #T),@SDV3=(SELECT AVG(S27) FROM #T)  
--ELSE IF @I3=29 SELECT @VAR3='OCCUP_1YRCH',@COEFF3=@X29,@MEAN3=(SELECT AVG(M29) FROM #T),@SDV3=(SELECT AVG(S29) FROM #T)  
--ELSE IF @I3=30 SELECT @VAR3='REV_1YR_PCT_CH',@COEFF3=@X30 ,@MEAN3=(SELECT AVG(M30) FROM #T),@SDV3=(SELECT AVG(S30) FROM #T)  
--ELSE IF @I3=31 SELECT @VAR3='EXP_1YR_PCT_CH',@COEFF3=@X31,@MEAN3=(SELECT AVG(M31) FROM #T),@SDV3=(SELECT AVG(S31) FROM #T)  
--ELSE IF @I3=34 SELECT @VAR3='YearBuilt',@COEFF3=@X34,@MEAN3=(SELECT AVG(M34) FROM #T),@SDV3=(SELECT AVG(S34) FROM #T)  
ELSE IF @I3=35 SELECT @VAR3='NumUnits',@COEFF3=@X35,@MEAN3=(SELECT AVG(M35) FROM #T),@SDV3=(SELECT AVG(S35) FROM #T)  
--ELSE IF @I3=36 SELECT @VAR3='RevenuePctMedianIncome',@COEFF3=@X36,@MEAN3=(SELECT AVG(M36) FROM #T),@SDV3=(SELECT AVG(S36) FROM #T)  
--ELSE IF @I3=38 SELECT @VAR3='NOI_1YR_PCT_CH',@COEFF3=@X38,@MEAN3=(SELECT AVG(M38) FROM #T),@SDV3=(SELECT AVG(S38) FROM #T)  
ELSE IF @I3=39 SELECT @VAR3='HPI_METRO_1YRCH',@COEFF3=@X39,@MEAN3=(SELECT AVG(M39) FROM #T),@SDV3=(SELECT AVG(S39) FROM #T)  

--ELSE IF @I3=20 SELECT @VAR3='RETAXES_PCTREV',@COEFF3=@X20,@MEAN3=(SELECT AVG(M20) FROM #T),@SDV3=(SELECT AVG(S20) FROM #T)  
--ELSE IF @I3=21 SELECT @VAR3='PROPINS_PCTREV',@COEFF3=@X21,@MEAN3=(SELECT AVG(M21) FROM #T),@SDV3=(SELECT AVG(S21) FROM #T)  
--ELSE IF @I3=40 SELECT @VAR3='UTILITI_PCTREV',@COEFF3=@X40,@MEAN3=(SELECT AVG(M40) FROM #T),@SDV3=(SELECT AVG(S40) FROM #T)  
--ELSE IF @I3=41 SELECT @VAR3='REPAIRS_PCTREV',@COEFF3=@X41,@MEAN3=(SELECT AVG(M41) FROM #T),@SDV3=(SELECT AVG(S41) FROM #T)  
--ELSE IF @I3=42 SELECT @VAR3='MANAGEM_PCTREV',@COEFF3=@X42,@MEAN3=(SELECT AVG(M42) FROM #T),@SDV3=(SELECT AVG(S42) FROM #T)  
--ELSE IF @I3=43 SELECT @VAR3='PAYROLL_PCTREV',@COEFF3=@X43,@MEAN3=(SELECT AVG(M43) FROM #T),@SDV3=(SELECT AVG(S43) FROM #T)  

IF @I4=1 SELECT @VAR4='YearBuiltRenov',@COEFF4=@X1 ,@MEAN4=(SELECT AVG(M1) FROM #T),@SDV4=(SELECT AVG(S1) FROM #T)  
ELSE IF @I4=2 SELECT @VAR4='PopulationPerSqMile',@COEFF4=@X2 ,@MEAN4=(SELECT AVG(M2) FROM #T),@SDV4=(SELECT AVG(S2) FROM #T)  
ELSE IF @I4=3 SELECT @VAR4='MedianHHInc',@COEFF4=@X3 ,@MEAN4=(SELECT AVG(M3) FROM #T),@SDV4=(SELECT AVG(S3) FROM #T)  
ELSE IF @I4=4 SELECT @VAR4='MedianHomeVal',@COEFF4=@X4 ,@MEAN4=(SELECT AVG(M4) FROM #T),@SDV4=(SELECT AVG(S4) FROM #T)  
ELSE IF @I4=5 SELECT @VAR4='Median_Rent',@COEFF4=@X5 ,@MEAN4=(SELECT AVG(M5) FROM #T),@SDV4=(SELECT AVG(S5) FROM #T)  
ELSE IF @I4=6 SELECT @VAR4='MedianAge',@COEFF4=@X6 ,@MEAN4=(SELECT AVG(M6) FROM #T),@SDV4=(SELECT AVG(S6) FROM #T)  
ELSE IF @I4=7 SELECT @VAR4='Median_Owner_Costs',@COEFF4=@X7 ,@MEAN4=(SELECT AVG(M7) FROM #T),@SDV4=(SELECT AVG(S7) FROM #T)  
ELSE IF @I4=8 SELECT @VAR4='RenterPCT',@COEFF4=@X8 ,@MEAN4=(SELECT AVG(M8) FROM #T),@SDV4=(SELECT AVG(S8) FROM #T)  
ELSE IF @I4=9 SELECT @VAR4='CashRentOver30PCT',@COEFF4=@X9 ,@MEAN4=(SELECT AVG(M9) FROM #T),@SDV4=(SELECT AVG(S9) FROM #T)  
ELSE IF @I4=10 SELECT @VAR4='BachelorsOrMorePCT',@COEFF4=@X10 ,@MEAN4=(SELECT AVG(M10) FROM #T),@SDV4=(SELECT AVG(S10) FROM #T)  
ELSE IF @I4=11 SELECT @VAR4='UnemploymentPCT',@COEFF4=@X11 ,@MEAN4=(SELECT AVG(M11) FROM #T),@SDV4=(SELECT AVG(S11) FROM #T)  
ELSE IF @I4=13 SELECT @VAR4='MngtFinancePCT',@COEFF4=@X13 ,@MEAN4=(SELECT AVG(M13) FROM #T),@SDV4=(SELECT AVG(S13) FROM #T)  
ELSE IF @I4=15 SELECT @VAR4='MovedIn2010orLaterPCT',@COEFF4=@X15 ,@MEAN4=(SELECT AVG(M15) FROM #T),@SDV4=(SELECT AVG(S15) FROM #T)  
ELSE IF @I4=16 SELECT @VAR4='HPI_1YRCH',@COEFF4=@X16 ,@MEAN4=(SELECT AVG(M16) FROM #T),@SDV4=(SELECT AVG(S16) FROM #T)  
--ELSE IF @I4=17 SELECT @VAR4='OCCUP',@COEFF4=@X17 ,@MEAN4=(SELECT AVG(M17) FROM #T),@SDV4=(SELECT AVG(S17) FROM #T)  
--ELSE IF @I4=18 SELECT @VAR4='REV_PERUNIT',@COEFF4=@X18,@MEAN4=(SELECT AVG(M18) FROM #T),@SDV4=(SELECT AVG(S18) FROM #T)  
--ELSE IF @I4=19 SELECT @VAR4='EXP_PCTREV',@COEFF4=@X19,@MEAN4=(SELECT AVG(M19) FROM #T),@SDV4=(SELECT AVG(S19) FROM #T)  
--ELSE IF @I4=27 SELECT @VAR4='CAPEX0_PCTREV',@COEFF4=@X27,@MEAN4=(SELECT AVG(M27) FROM #T),@SDV4=(SELECT AVG(S27) FROM #T)  
--ELSE IF @I4=29 SELECT @VAR4='OCCUP_1YRCH',@COEFF4=@X29,@MEAN4=(SELECT AVG(M29) FROM #T),@SDV4=(SELECT AVG(S29) FROM #T)  
--ELSE IF @I4=30 SELECT @VAR4='REV_1YR_PCT_CH',@COEFF4=@X30 ,@MEAN4=(SELECT AVG(M30) FROM #T),@SDV4=(SELECT AVG(S30) FROM #T)  
--ELSE IF @I4=31 SELECT @VAR4='EXP_1YR_PCT_CH',@COEFF4=@X31,@MEAN4=(SELECT AVG(M31) FROM #T),@SDV4=(SELECT AVG(S31) FROM #T)  
--ELSE IF @I4=34 SELECT @VAR4='YearBuilt',@COEFF4=@X34,@MEAN4=(SELECT AVG(M34) FROM #T),@SDV4=(SELECT AVG(S34) FROM #T)  
ELSE IF @I4=35 SELECT @VAR4='NumUnits',@COEFF4=@X35,@MEAN4=(SELECT AVG(M35) FROM #T),@SDV4=(SELECT AVG(S35) FROM #T)  
--ELSE IF @I4=36 SELECT @VAR4='RevenuePctMedianIncome',@COEFF4=@X36,@MEAN4=(SELECT AVG(M36) FROM #T),@SDV4=(SELECT AVG(S36) FROM #T)  
--ELSE IF @I4=38 SELECT @VAR4='NOI_1YR_PCT_CH',@COEFF4=@X38,@MEAN4=(SELECT AVG(M38) FROM #T),@SDV4=(SELECT AVG(S38) FROM #T)  
ELSE IF @I4=39 SELECT @VAR4='HPI_METRO_1YRCH',@COEFF4=@X39,@MEAN4=(SELECT AVG(M39) FROM #T),@SDV4=(SELECT AVG(S39) FROM #T)  

--ELSE IF @I4=20 SELECT @VAR4='RETAXES_PCTREV',@COEFF4=@X20,@MEAN4=(SELECT AVG(M20) FROM #T),@SDV4=(SELECT AVG(S20) FROM #T)  
--ELSE IF @I4=21 SELECT @VAR4='PROPINS_PCTREV',@COEFF4=@X21,@MEAN4=(SELECT AVG(M21) FROM #T),@SDV4=(SELECT AVG(S21) FROM #T)  
--ELSE IF @I4=40 SELECT @VAR4='UTILITI_PCTREV',@COEFF4=@X40,@MEAN4=(SELECT AVG(M40) FROM #T),@SDV4=(SELECT AVG(S40) FROM #T)  
--ELSE IF @I4=41 SELECT @VAR4='REPAIRS_PCTREV',@COEFF4=@X41,@MEAN4=(SELECT AVG(M41) FROM #T),@SDV4=(SELECT AVG(S41) FROM #T)  
--ELSE IF @I4=42 SELECT @VAR4='MANAGEM_PCTREV',@COEFF4=@X42,@MEAN4=(SELECT AVG(M42) FROM #T),@SDV4=(SELECT AVG(S42) FROM #T)  
--ELSE IF @I4=43 SELECT @VAR4='PAYROLL_PCTREV',@COEFF4=@X43,@MEAN4=(SELECT AVG(M43) FROM #T),@SDV4=(SELECT AVG(S43) FROM #T)  

IF @I5=1 SELECT @VAR5='YearBuiltRenov',@COEFF5=@X1 ,@MEAN5=(SELECT AVG(M1) FROM #T),@SDV5=(SELECT AVG(S1) FROM #T)  
ELSE IF @I5=2 SELECT @VAR5='PopulationPerSqMile',@COEFF5=@X2 ,@MEAN5=(SELECT AVG(M2) FROM #T),@SDV5=(SELECT AVG(S2) FROM #T)  
ELSE IF @I5=3 SELECT @VAR5='MedianHHInc',@COEFF5=@X3 ,@MEAN5=(SELECT AVG(M3) FROM #T),@SDV5=(SELECT AVG(S3) FROM #T)  
ELSE IF @I5=4 SELECT @VAR5='MedianHomeVal',@COEFF5=@X4 ,@MEAN5=(SELECT AVG(M4) FROM #T),@SDV5=(SELECT AVG(S4) FROM #T)  
ELSE IF @I5=5 SELECT @VAR5='Median_Rent',@COEFF5=@X5 ,@MEAN5=(SELECT AVG(M5) FROM #T),@SDV5=(SELECT AVG(S5) FROM #T)  
ELSE IF @I5=6 SELECT @VAR5='MedianAge',@COEFF5=@X6 ,@MEAN5=(SELECT AVG(M6) FROM #T),@SDV5=(SELECT AVG(S6) FROM #T)  
ELSE IF @I5=7 SELECT @VAR5='Median_Owner_Costs',@COEFF5=@X7 ,@MEAN5=(SELECT AVG(M7) FROM #T),@SDV5=(SELECT AVG(S7) FROM #T)  
ELSE IF @I5=8 SELECT @VAR5='RenterPCT',@COEFF5=@X8 ,@MEAN5=(SELECT AVG(M8) FROM #T),@SDV5=(SELECT AVG(S8) FROM #T)  
ELSE IF @I5=9 SELECT @VAR5='CashRentOver30PCT',@COEFF5=@X9 ,@MEAN5=(SELECT AVG(M9) FROM #T),@SDV5=(SELECT AVG(S9) FROM #T)  
ELSE IF @I5=10 SELECT @VAR5='BachelorsOrMorePCT',@COEFF5=@X10 ,@MEAN5=(SELECT AVG(M10) FROM #T),@SDV5=(SELECT AVG(S10) FROM #T)  
ELSE IF @I5=11 SELECT @VAR5='UnemploymentPCT',@COEFF5=@X11 ,@MEAN5=(SELECT AVG(M11) FROM #T),@SDV5=(SELECT AVG(S11) FROM #T)  
ELSE IF @I5=13 SELECT @VAR5='MngtFinancePCT',@COEFF5=@X13 ,@MEAN5=(SELECT AVG(M13) FROM #T),@SDV5=(SELECT AVG(S13) FROM #T)  
ELSE IF @I5=15 SELECT @VAR5='MovedIn2010orLaterPCT',@COEFF5=@X15 ,@MEAN5=(SELECT AVG(M15) FROM #T),@SDV5=(SELECT AVG(S15) FROM #T)  
ELSE IF @I5=16 SELECT @VAR5='HPI_1YRCH',@COEFF5=@X16 ,@MEAN5=(SELECT AVG(M16) FROM #T),@SDV5=(SELECT AVG(S16) FROM #T)  
--ELSE IF @I5=17 SELECT @VAR5='OCCUP',@COEFF5=@X17 ,@MEAN5=(SELECT AVG(M17) FROM #T),@SDV5=(SELECT AVG(S17) FROM #T)  
--ELSE IF @I5=18 SELECT @VAR5='REV_PERUNIT',@COEFF5=@X18,@MEAN5=(SELECT AVG(M18) FROM #T),@SDV5=(SELECT AVG(S18) FROM #T)  
--ELSE IF @I5=19 SELECT @VAR5='EXP_PCTREV',@COEFF5=@X19,@MEAN5=(SELECT AVG(M19) FROM #T),@SDV5=(SELECT AVG(S19) FROM #T)  
--ELSE IF @I5=27 SELECT @VAR5='CAPEX0_PCTREV',@COEFF5=@X27,@MEAN5=(SELECT AVG(M27) FROM #T),@SDV5=(SELECT AVG(S27) FROM #T)  
--ELSE IF @I5=29 SELECT @VAR5='OCCUP_1YRCH',@COEFF5=@X29,@MEAN5=(SELECT AVG(M29) FROM #T),@SDV5=(SELECT AVG(S29) FROM #T)  
--ELSE IF @I5=30 SELECT @VAR5='REV_1YR_PCT_CH',@COEFF5=@X30 ,@MEAN5=(SELECT AVG(M30) FROM #T),@SDV5=(SELECT AVG(S30) FROM #T)  
--ELSE IF @I5=31 SELECT @VAR5='EXP_1YR_PCT_CH',@COEFF5=@X31,@MEAN5=(SELECT AVG(M31) FROM #T),@SDV5=(SELECT AVG(S31) FROM #T)  
--ELSE IF @I5=34 SELECT @VAR5='YearBuilt',@COEFF5=@X34,@MEAN5=(SELECT AVG(M34) FROM #T),@SDV5=(SELECT AVG(S34) FROM #T)  
ELSE IF @I5=35 SELECT @VAR5='NumUnits',@COEFF5=@X35,@MEAN5=(SELECT AVG(M35) FROM #T),@SDV5=(SELECT AVG(S35) FROM #T)  
--ELSE IF @I5=36 SELECT @VAR5='RevenuePctMedianIncome',@COEFF5=@X36,@MEAN5=(SELECT AVG(M36) FROM #T),@SDV5=(SELECT AVG(S36) FROM #T)  
--ELSE IF @I5=38 SELECT @VAR5='NOI_1YR_PCT_CH',@COEFF5=@X38,@MEAN5=(SELECT AVG(M38) FROM #T),@SDV5=(SELECT AVG(S38) FROM #T)  
ELSE IF @I5=39 SELECT @VAR5='HPI_METRO_1YRCH',@COEFF5=@X39,@MEAN5=(SELECT AVG(M39) FROM #T),@SDV5=(SELECT AVG(S39) FROM #T)  

--ELSE IF @I5=20 SELECT @VAR5='RETAXES_PCTREV',@COEFF5=@X20,@MEAN5=(SELECT AVG(M20) FROM #T),@SDV5=(SELECT AVG(S20) FROM #T)  
--ELSE IF @I5=21 SELECT @VAR5='PROPINS_PCTREV',@COEFF5=@X21,@MEAN5=(SELECT AVG(M21) FROM #T),@SDV5=(SELECT AVG(S21) FROM #T)  
--ELSE IF @I5=40 SELECT @VAR5='UTILITI_PCTREV',@COEFF5=@X40,@MEAN5=(SELECT AVG(M40) FROM #T),@SDV5=(SELECT AVG(S40) FROM #T)  
--ELSE IF @I5=41 SELECT @VAR5='REPAIRS_PCTREV',@COEFF5=@X41,@MEAN5=(SELECT AVG(M41) FROM #T),@SDV5=(SELECT AVG(S41) FROM #T)  
--ELSE IF @I5=42 SELECT @VAR5='MANAGEM_PCTREV',@COEFF5=@X42,@MEAN5=(SELECT AVG(M42) FROM #T),@SDV5=(SELECT AVG(S42) FROM #T)  
--ELSE IF @I5=43 SELECT @VAR5='PAYROLL_PCTREV',@COEFF5=@X43,@MEAN5=(SELECT AVG(M43) FROM #T),@SDV5=(SELECT AVG(S43) FROM #T)  


	END
	DROP TABLE #T
END--NUMPROPYEAR (NOT NULL)
END--BEGIN CALC

--SELECT @RSQUARE, @RSQUARE1,@RSQUARE2,@RSQUARE3,@RSQUARE4,@RSQUARE5 
IF @RSQUARE>0
BEGIN

DELETE FROM PROP_REGRESS_EACH_YEAR WHERE MDRA_SUBTYPE_YR1_YR2_VAR_NUM=@MDRA_SUBTYPE_YR1_YR2_VAR_NUM
INSERT INTO PROP_REGRESS_EACH_YEAR
(MDRA_SUBTYPE_YR1_YR2_VAR_NUM,
NARRATIVE,
MDRA_SUBTYPE_YR1_YR2,
MDRA_SUBTYPE_YR2_VAR,
MDRA_SUBTYPE_VAR,
MDRA_SUBTYPE_YR2,
MDRA,
SUBTYPE,
STATEMENTYEAR1,
STATEMENTYEAR2,
NumYears,
NumObservations,
DEPVAR,
MODELNUM,
MEAN,
SDV,
STDERROR,
RSQUARE,
VAR1,
MEAN1,
SDV1,
COEFF1,
STDERROR1,
RSQUARE1,
VAR2,
MEAN2,
SDV2,
COEFF2,
STDERROR2,
RSQUARE2,
VAR3,
MEAN3,
SDV3,
COEFF3,
STDERROR3,
RSQUARE3,
VAR4,
MEAN4,
SDV4,
COEFF4,
STDERROR4,
RSQUARE4,
VAR5,
MEAN5,
SDV5,
COEFF5,
STDERROR5,
RSQUARE5)

SELECT
@MDRA_SUBTYPE_YR1_YR2_VAR_NUM AS MDRA_SUBTYPE_YR1_YR2_VAR_NUM,
CONCAT(@MDRA_SUBTYPE_YR1_YR2_VAR_NUM,'_',CURRENT_TIMESTAMP),
@MDRA_SUBTYPE_YR1_YR2 AS MDRA_SUBTYPE_YR1_YR2,
@MDRA_SUBTYPE_YR2_VAR AS MDRA_SUBTYPE_YR2_VAR,
@MDRA_SUBTYPE_VAR AS MDRA_SUBTYPE_VAR,
@MDRA_SUBTYPE_YR2 AS MDRA_SUBTYPE_YR2,
@MDRA AS MDRA,
@SUBTYPE AS SUBTYPE,
@STATEMENTYEAR1 AS STATEMENTYEAR1,
@STATEMENTYEAR2 AS STATEMENTYEAR2,
@STATEMENTYEAR2-@STATEMENTYEAR1 + 1 AS NUMYEARS,
@NUMPROPERTIES AS NUMPROPERTIES,
@DEPVAR AS DEPVAR,
--@DATACATEGORY AS DATACATEGORY,
@MODELNUM AS MODELNUM,
@MEAN0 AS MEAN0,
@SDV0 AS SDV0,
@STDERROR AS STDERROR,
@RSQUARE AS RSQUARE,
@VAR1 AS VAR1,
@MEAN1 AS MEAN1,
@SDV1 AS SDV1,
@COEFF1 AS COEFF1,
@STDERROR1 AS STDERROR1,
@RSQUARE1 AS RSQUARE1,
@VAR2 AS VAR2,
@MEAN2 AS MEAN2,
@SDV2 AS SDV2,
@COEFF2 AS COEFF2,
@STDERROR2 AS STDERROR2,
@RSQUARE2 AS RSQUARE2,
@VAR3 AS VAR3,
@MEAN3 AS MEAN3,
@SDV3 AS SDV3,
@COEFF3 AS COEFF3,
@STDERROR3 AS STDERROR3,
@RSQUARE3 AS RSQUARE3,
@VAR4 AS VAR4,
@MEAN4 AS MEAN4,
@SDV4 AS SDV4,
@COEFF4 AS COEFF4,
@STDERROR4 AS STDERROR4,
@RSQUARE4 AS RSQUARE4,
@VAR5 AS VAR5,
@MEAN5 AS MEAN5,
@SDV5 AS SDV5,
@COEFF5 AS COEFF5,
@STDERROR5 AS STDERROR5,
@RSQUARE5 AS RSQUARE5

DECLARE @RUNTIME datetime2(7) 
SELECT @RUNTIME=CURRENT_TIMESTAMP
INSERT INTO LOADLOG(ANALYST_RUNTIME_TN_EXA_NUMROWS,RUNTIME,TABLENAME,NUMROWS) 
SELECT CONCAT(@RUNTIME,'_PROP_REGRESS_EACH_YEAR_',(SELECT COUNT(*) FROM PROP_REGRESS_EACH_YEAR),'_REGRESS'),@RUNTIME,CONCAT('PROP_REGRESS_EACH_YEAR_REGRESS_',@MDRA_SUBTYPE_YR1_YR2_VAR_NUM),(SELECT COUNT(*) FROM PROP_REGRESS_EACH_YEAR WHERE MEAN IS NOT NULL)

END

END TRY

BEGIN CATCH
    SELECT 
     ERROR_NUMBER() AS ErrorNumber
    ,ERROR_SEVERITY() AS ErrorSeverity
    ,ERROR_STATE() AS ErrorState
    ,ERROR_PROCEDURE() AS ErrorProcedure
    ,ERROR_LINE() AS ErrorLine
    ,ERROR_MESSAGE() AS ErrorMessage
END CATCH

END
