-- Francisco: Excute UPADE_LPLIST_GEO_EXTERNAL, INSERT_PROPTOKEN, INSERT_CENSUSDATA_FROM_CENSUSTRACTS and UPDATE LPLIST_ALL
-- Francisco: NEEDS TO BE DETAILED
---DROP PROCEDURE A_2_051822
CREATE PROCEDURE [dbo].[A_2_051822]
       
AS

BEGIN

BEGIN TRY
----
DECLARE @TIMESTAMP_LAST DATETIME2(7) SELECT @TIMESTAMP_LAST=CURRENT_TIMESTAMP

SELECT CONCAT('STEP#7:LPLIST_ALL - UPDATE LAT/LONG FOR PROPERTIES NOT ON PROPTOKEN/RUNTIME(SEC)=', DATEDIFF(S,@TIMESTAMP_LAST,CURRENT_TIMESTAMP)) SELECT @TIMESTAMP_LAST=CURRENT_TIMESTAMP
EXECUTE UPDATE_LPLIST_GEO_EXTERNAL
DELETE FROM LPLIST_ALL WHERE LATITUDE IS NULL OR LONGITUDE IS NULL OR LATITUDE=0 OR LONGITUDE=0 

SELECT CONCAT('STEP#7:LPLIST_ALL - INSERT PROPTOKENS FOR NEW PROPERTIES/RUNTIME(SEC)=', DATEDIFF(S,@TIMESTAMP_LAST,CURRENT_TIMESTAMP)) SELECT @TIMESTAMP_LAST=CURRENT_TIMESTAMP
EXECUTE INSERT_PROPTOKEN

SELECT CONCAT('STEP#8:INSERT NEW EXID_PLID_PRID INTO CENSUSDATA TABLES; COMPLETE/END/RUNTIME(SEC)=', DATEDIFF(S,@TIMESTAMP_LAST,CURRENT_TIMESTAMP)) SELECT @TIMESTAMP_LAST=CURRENT_TIMESTAMP
EXECUTE INSERT_CENSUSDATA_FROM_CENSUSTRACTS


UPDATE LPLIST_ALL SET
NCREIFRegion=P.NCREIFRegion,
NCREIFDivision=P.NCREIFDivision, 
NCREIFMetro=P.NCREIFMetro, 
SAMEGEO=P.SAMEGEO,
SAMEPROPERTYID=P.SAMEPROPERTYID
FROM PROPTOKEN P WHERE P.DATASOURCEID=LPLIST_ALL.EXID_PLID_PRID

UPDATE LPLIST_ALL SET NUM_LOANS_ACTIVE=(SELECT COUNT(DISTINCT LOANID) FROM LPLIST_ALL X WHERE X.SAMEPROPERTYID=LPLIST_ALL.SAMEPROPERTYID AND X.CURRENTENDINGSCHEDBAL>0)
UPDATE LPLIST_ALL SET NUM_LOANS=(SELECT COUNT(DISTINCT LOANID) FROM LPLIST_ALL X WHERE X.SAMEPROPERTYID=LPLIST_ALL.SAMEPROPERTYID)
UPDATE LPLIST_ALL SET NUM_PROPS=(SELECT COUNT(DISTINCT SAMEPROPERTYID) FROM LPLIST_ALL X WHERE X.LOANID=LPLIST_ALL.LOANID)

END TRY

BEGIN CATCH
    SELECT 
     ERROR_NUMBER() AS ErrorNumber
    ,ERROR_SEVERITY() AS ErrorSeverity
    ,ERROR_STATE() AS ErrorState
    ,ERROR_PROCEDURE() AS ErrorProcedure
    ,ERROR_LINE() AS ErrorLine
    ,ERROR_MESSAGE() AS ErrorMessage
END CATCH

END
