
---DROP PROCEDURE A_6_030522
CREATE PROCEDURE [dbo].[A_6_030522] @MAXYEAR INT,@MINYEAR INT
       
AS

BEGIN

BEGIN TRY
----


DECLARE @TIMESTAMP_LAST DATETIME2(7) SELECT @TIMESTAMP_LAST=CURRENT_TIMESTAMP
SELECT CONCAT('INSERT_LOAN_CALCS... /RUNTIME(SEC)=', DATEDIFF(S,@TIMESTAMP_LAST,CURRENT_TIMESTAMP)) SELECT @TIMESTAMP_LAST=CURRENT_TIMESTAMP

DECLARE  @YEAR2 INT
SELECT @YEAR2=@MAXYEAR
WHILE @YEAR2>=@MINYEAR
BEGIN 
EXECUTE INSERT_LOAN_CALCS_YEAR @YEAR2
SELECT @YEAR2=@YEAR2-1
END

EXECUTE UPDATE_LOAN_CALCS_AVM

SELECT CONCAT('COMPLETE INSERT_LOAN_CALCS /RUNTIME(SEC)=', DATEDIFF(S,@TIMESTAMP_LAST,CURRENT_TIMESTAMP)) SELECT @TIMESTAMP_LAST=CURRENT_TIMESTAMP


END TRY

BEGIN CATCH
    SELECT 
     ERROR_NUMBER() AS ErrorNumber
    ,ERROR_SEVERITY() AS ErrorSeverity
    ,ERROR_STATE() AS ErrorState
    ,ERROR_PROCEDURE() AS ErrorProcedure
    ,ERROR_LINE() AS ErrorLine
    ,ERROR_MESSAGE() AS ErrorMessage
END CATCH

END